services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"  # Проброс порта 443
    image: my-image-name
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
